global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'javasight-processs-scala'
    static_configs:
      - targets: ['host.docker.internal:9095']
        labels:
          service: 'javasight-process-scala'
          instance: 'local'
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
